name: Create Release Pull Request
on:
  pull_request:

jobs:
  release-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: mondeja/release-action@fix-release
        name: Create release pull request
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
